---
- name: Adiciona grupo tomcat
  group:
    name: tomcat
    state: present

- name: Adiciona usuario tomcat
  user:
    name: tomcat
    state: present

- name: Instala pacote yum-utils
  yum:
    name: 'yum-utils'
    state: present

- name: Instala Java
  yum:
    name: "{{ java }}"
    state: latest
      
- name: Baixa o arquivo de instalacao do tomcat
  get_url:
    url: "{{ tomcat_wget }}"
    dest: '/tmp/tomcat.tar.gz'

- name: 'Cria o diretório do Tomcat'
  file:
    path: /usr/local/tomcat
    state: directory
    mode: 0755

- name: Descompacta o tomcat
  unarchive:
    src: '/tmp/tomcat.tar.gz'
    dest: /usr/local/tomcat
    extra_opts: [--strip-components=1]
    remote_src: yes
    group: tomcat
    owner: tomcat
