- name: Adiciona usuarios dev ao grupo tomcat
  command: usermod -aG tomcat {{ item.id }}
  with_items: "{{ devuser }}"

- name: Copia arquivo de permissão para usuários dev para o sudoers.d
  copy:
    src: files/dev_sudoers_tomcat
    dest: /etc/sudoers.d
  become: yes
  tags: user


